vim.cmd('colorscheme shirotelin')
vim.cmd [[hi Normal guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi LineNr guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi CursorLineNr guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi ColorColumn guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi DiffText guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi Folded guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi FoldColumn guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi SignColumn guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi StatusLine guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
--vim.cmd [[hi PMenu guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
--vim.cmd [[hi PMenuSel guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
--vim.cmd [[hi StatusLine guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
--vim.cmd [[hi StatusLineNC guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi EndOfBuffer guibg=NONE ctermbg=NONE gui=NONE cterm=NONE]]
vim.cmd [[hi Comment  guifg=#666666 ctermfg=darkgrey cterm=italic gui=italic]]
vim.cmd [[hi cComment guifg=#666666 ctermfg=darkgrey cterm=italic gui=italic]]
vim.cmd [[hi clear CursorLine]]
vim.cmd [[hi CursorLine gui=underline cterm=underline guisp=gray40]]
vim.cmd [[hi clear TabLineFill]]
vim.cmd [[hi clear TabLine]]
vim.cmd [[hi clear Title]]
vim.cmd [[hi TabLineSel cterm=bold gui=bold]]
vim.cmd [[hi DiagnosticInfo  guifg=#666666 ctermfg=darkgrey cterm=italic gui=italic]]
vim.cmd [[hi DiagnosticWarn  guifg=#cc0000 ctermfg=darkgrey cterm=italic gui=italic]]
vim.cmd [[hi DiagnosticHint  guifg=#5566bb ctermfg=darkgrey cterm=italic gui=italic]]
vim.cmd [[hi DiagnosticOk    guifg=#666666 ctermfg=darkgrey cterm=italic gui=italic]]
--vim.cmd [[hi NormalFloat guibg=#333333, ctermbg=gray]] 
--vim.cmd [[hi FloatBorder guifg=#444488 guibg=#eeeeee]]
vim.cmd [[hi FloatBorder guifg=#444488 guibg=none]]
vim.cmd [[hi Pmenu guibg=none]]
