alias sm="ssh -p 2022 localhost"
alias addkeys="ssh-add ~/.ssh/id_ed25519 ~/.ssh/id_rsa"
alias r="ranger"
alias um="udiskie-umount"
alias btop="bpytop"
alias ben="~/git/benny_converter/benny_conv.py"
alias vdf="/mnt/ssd/crf_test/cmp.sh"
alias v="~/nvim.appimage"
alias n="~/nvim.appimage ~/git/memo/memo.md"
alias cat="batcat"
alias vbash="~/nvim.appimage ~/git/dotfiles/bash && source ~/.bashrc"
alias start_ai="firejail --whitelist=/home/sav/.bin /home/sav/.bin/tgpt -i"
#alias k="(nohup kitty > /dev/null &) && exit"
