alias sm="ssh -p 2022 localhost"
alias addkeys="ssh-add ~/.ssh/id_ed25519 ~/.ssh/id_rsa"
alias r='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias um="udiskie-umount"
alias btop="bpytop"
alias ben="~/git/benny_converter/benny_conv.py"
alias vdf="/mnt/ssd/crf_test/cmp.sh"
alias v="~/nvim.appimage"
alias n="~/nvim.appimage ~/git/memo/memo.md"
alias cat="batcat"
alias vbash="~/nvim.appimage ~/git/dotfiles/bash && source ~/.bashrc"
alias start_ai="firejail --whitelist=/home/sav/.bin /home/sav/.bin/tgpt -i"
#alias k="(nohup kitty > /dev/null &) && exit"
WP_RESOLUTION="3840x2160"
alias wp="/home/sav/git/xwinwrap/xwinwrap -g $WP_RESOLUTION -ni -s -nf -b -un -ov -fdt -argb -- mpv --mute=yes --no-audio --no-osc --no-osd-bar --quiet --screen=0 --geometry=$WP_RESOLUTION+0+0 -wid WID --loop"
