alias sm="ssh -p 2022 localhost"
alias addkeys="ssh-add ~/.ssh/id_ed25519 ~/.ssh/id_rsa"
alias r='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias um="udiskie-umount"
alias btop="bpytop"
alias ben="~/git/benny_converter/benny_conv.py"
alias vdf="/mnt/ssd/crf_test/cmp.sh"
alias v="~/.bin/nvim.appimage"
alias n="~/.bin/nvim.appimage ~/git/memo/memo.md"
alias cat="batcat"
alias vbash="~/.bin/nvim.appimage ~/git/dotfiles/bash && source ~/.bashrc"
alias ai="firejail --whitelist=/home/sav/.bin /home/sav/.bin/tgpt -i"
alias toggle_light="source ~/git/dotfiles/bash/toggle_light.sh"

alias cpu_slow="sudo cpupower frequency-set --min 400mhz --max 800mhz --related"
alias cpu_fast="sudo cpupower frequency-set --min 400mhz --max 4200mhz --related"
WP_RESOLUTION="3840x2160"
alias wp="/home/sav/git/xwinwrap/xwinwrap -g $WP_RESOLUTION -ni -s -nf -b -un -ov -fdt -argb -- mpv --mute=yes --no-audio --no-osc --no-osd-bar --quiet --screen=0 --geometry=$WP_RESOLUTION+0+0 -wid WID --loop"
